# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\"%\n\x0e\x41\x63\x63ountRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"L\n\x0f\x41\x63\x63ountResponse\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\"\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x0c.Transaction\"Y\n\x0bTransaction\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x18\n\x10transaction_type\x18\x04 \x01(\t2N\n\x12\x41\x63\x63ountServiceGrpc\x12\x38\n\x13getAccountStatement\x12\x0f.AccountRequest\x1a\x10.AccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=17
  _globals['_ACCOUNTREQUEST']._serialized_end=54
  _globals['_ACCOUNTRESPONSE']._serialized_start=56
  _globals['_ACCOUNTRESPONSE']._serialized_end=132
  _globals['_TRANSACTION']._serialized_start=134
  _globals['_TRANSACTION']._serialized_end=223
  _globals['_ACCOUNTSERVICEGRPC']._serialized_start=225
  _globals['_ACCOUNTSERVICEGRPC']._serialized_end=303
# @@protoc_insertion_point(module_scope)
